"""changes

Revision ID: 207f1f7e920b
Revises: c156e2df4495
Create Date: 2018-03-11 20:09:34.322146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207f1f7e920b'
down_revision = 'c156e2df4495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliver',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senduser', sa.String(length=24), nullable=True),
    sa.Column('job', sa.String(length=24), nullable=True),
    sa.Column('receivecompany', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliver')
    # ### end Alembic commands ###
