"""changes

Revision ID: 475a782f56ce
Revises: 544bc32dbf98
Create Date: 2018-03-22 15:45:48.780481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '475a782f56ce'
down_revision = '544bc32dbf98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('major', sa.String(length=24), nullable=True))
    op.drop_column('resume', 'magor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('magor', mysql.VARCHAR(length=24), nullable=True))
    op.drop_column('resume', 'major')
    # ### end Alembic commands ###
