"""changes

Revision ID: 544bc32dbf98
Revises: 4512d6e5e8f2
Create Date: 2018-03-22 15:26:28.640702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '544bc32dbf98'
down_revision = '4512d6e5e8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('college', sa.String(length=24), nullable=True))
    op.add_column('resume', sa.Column('magor', sa.String(length=24), nullable=True))
    op.drop_column('resume', 'exprience')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('exprience', mysql.VARCHAR(length=254), nullable=True))
    op.drop_column('resume', 'magor')
    op.drop_column('resume', 'college')
    # ### end Alembic commands ###
