"""changes

Revision ID: 848b4cf3b762
Revises: 207f1f7e920b
Create Date: 2018-03-14 13:17:59.034443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '848b4cf3b762'
down_revision = '207f1f7e920b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliver', 'job')
    op.drop_column('deliver', 'job_id')
    op.drop_column('deliver', 'senduser')
    op.drop_column('deliver', 'receivecompany')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliver', sa.Column('receivecompany', mysql.VARCHAR(length=24), nullable=True))
    op.add_column('deliver', sa.Column('senduser', mysql.VARCHAR(length=24), nullable=True))
    op.add_column('deliver', sa.Column('job_id', mysql.VARCHAR(length=24), nullable=True))
    op.add_column('deliver', sa.Column('job', mysql.VARCHAR(length=24), nullable=True))
    # ### end Alembic commands ###
