"""changes

Revision ID: c156e2df4495
Revises: e0fed5d2702a
Create Date: 2018-03-10 20:54:36.759528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c156e2df4495'
down_revision = 'e0fed5d2702a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('condition', sa.String(length=256), nullable=True))
    op.drop_column('job', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('tags', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('job', 'condition')
    # ### end Alembic commands ###
