"""changes

Revision ID: c1c69b5cb36c
Revises: d6b511d9cdd0
Create Date: 2018-03-16 15:46:14.625013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c69b5cb36c'
down_revision = 'd6b511d9cdd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'company_id')
    # ### end Alembic commands ###
