"""changes

Revision ID: d6b511d9cdd0
Revises: 848b4cf3b762
Create Date: 2018-03-14 13:21:53.949510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b511d9cdd0'
down_revision = '848b4cf3b762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliver', sa.Column('job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deliver', 'job', ['job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deliver', type_='foreignkey')
    op.drop_column('deliver', 'job_id')
    # ### end Alembic commands ###
